/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

import { createClient } from "@supabase/supabase-js";

// @ts-ignore: Deno is a global in Supabase Functions
const client = () => createClient(
  // @ts-ignore: Deno is a global in Supabase Functions
  Deno.env.get("SUPABASE_URL"),
  // @ts-ignore: Deno is a global in Supabase Functions
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c3d27de3").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_c3d27de3").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c3d27de3").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c3d27de3").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_c3d27de3").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  // CORREÇÃO: Adicionado o tipo 'any' para o parâmetro 'd'
  return data?.map((d: any) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c3d27de3").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_c3d27de3").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  // CORREÇÃO: Adicionado o tipo 'any' para o parâmetro 'd'
  return data?.map((d: any) => d.value) ?? [];
};